### ISSUE TITLE
Error Docker with an EntryPoint

### ISSUE THREAD

**Issue by Nilad** [rrwick/Unicycler#123]
Hi, 

I started to work with your really perfect pipeline (for my work) :)

I make my own DockerFile for Unicycler. It will work perfectly and if i launch unicycler from the docker container but if i use an entrypoint like in this command :

  `docker run --name unicycler --rm \
> -v "Somesvolumes with the files and the outputdir"
> -it unicycler:latest \
> -1 /path/illumina_R1_001.fastq.gz \
> -2 /path/illumina_R2_001.fastq.gz \
> -l /path/minion/BC01.fastq \
> -o /path_outdir/BC01 > report_unicycler_BC01.txt`

I get this error in the `report_unicycler_BC01.txt` file : 

`Starting Unicycler (2018-07-26 07:50:41)
Traceback (most recent call last):
  File "/usr/local/bin/unicycler", line 9, in <module>
    load_entry_point('unicycler==0.4.6', 'console_scripts', 'unicycler')()
  File "/usr/local/lib/python3.5/dist-packages/unicycler/unicycler.py", line 66, in main
    print_intro_message(args, full_command, out_dir_message)
  File "/usr/local/lib/python3.5/dist-packages/unicycler/unicycler.py", line 704, in print_intro_message
    log.log_explanation(intro_message, extra_empty_lines_after=0)
  File "/usr/local/lib/python3.5/dist-packages/unicycler/log.py", line 132, in log_explanation
    for line in textwrap.wrap(text, width=terminal_width - 1):
  File "/usr/lib/python3.5/textwrap.py", line 380, in wrap
    return w.wrap(text)
  File "/usr/lib/python3.5/textwrap.py", line 355, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/lib/python3.5/textwrap.py", line 249, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -1 (must be > 0)`

If you want some other informations, please tell me.

**Comment by greatfireball** [comment]
Just to give a little response... I had a similar problem and solved it by using the `unbuffer` command.
