### ISSUE TITLE
Problem using "--existing_long_read_assembly"  from CANU

### ISSUE THREAD

**Issue by Kirk3gaard** [rrwick/Unicycler#133]
Hi Ryan

I have tried running unicycler (Unicycler v0.4.6) with the "--existing_long_read_assembly" option and the contigs.gfa file from CANU. However, I get the error below. My command for running unicycler is:

unicycler -1 $ILR1 -2 $ILR2 -l $READS --existing_long_read_assembly $LONGREF --threads $THREADS --spades_path $SPADES --no_correct --min_kmer_frac 0.3 --kmer_count 3 --no_pilon --mode bold --racon_path $RACON --keep 3 -o myfolder

Have you tried using the GFA from CANU for the assembly step? Should there be some formatting of the GFA before it works with Unicycler or is it something different that I am doing wrong?

Best regards 
Rasmus

`Using provided long read assembly instead of running Racon: bin1//temp/canu/CANU.contigs.gfa

Traceback (most recent call last):
  File "/space/sharedbin/bin/unicycler", line 21, in <module>
    main()
  File "/space/sharedbin/Unicycler_0.4.6/Unicycler-0.4.6/unicycler/unicycler.py", line 149, in main
    anchor_segments, args.existing_long_read_assembly)
  File "/space/sharedbin/Unicycler_0.4.6/Unicycler-0.4.6/unicycler/miniasm_assembly.py", line 201, in make_miniasm_string_graph
    unitig_graph = StringGraph(existing_long_read_assembly)
  File "/space/sharedbin/Unicycler_0.4.6/Unicycler-0.4.6/unicycler/string_graph.py", line 47, in __init__
    self.load_from_gfa(filename)
  File "/space/sharedbin/Unicycler_0.4.6/Unicycler-0.4.6/unicycler/string_graph.py", line 72, in load_from_gfa
    seg_1_to_seg_2_overlap = int(line_parts[5][:-1])
ValueError: invalid literal for int() with base 10: '7M1I6M1D45M1I104M3I91M1D693M1I138M1I13M1I760M1D63M2I94M1I168M1D6M1D31M1I217M3I251M3I37M1I35M1I180M1I292M1D151M1I5M1I156M1I347M1I62M1D452M1I1M1D281M1I13M1D154M3I82M1I1M2I425M1I84M2D241M1D134M1D2M1I7M1`

**Comment by thsyd** [comment]
Hi Rasmus,
Running in to the same problems. Is it covered in this thread? 
https://github.com/rrwick/Unicycler/issues/93

**Comment by Kirk3gaard** [comment]
Hi 
Thanks for pointing me towards that post 👍
