### ISSUE TITLE
Spades assembly failed error code 255

### ISSUE THREAD

**Issue by raw937** [rrwick/Unicycler#152]
Hello, 

I have tried this a couple of times and spades (in unicycler) failed to produce an assembly. 

Error log:
== Running assembler: K27

  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  74)   Loaded config from /data/friesen/testdrive/agro-dir/spades_assembly/assembly/K27/configs/config.info
  0:00:00.000     4M / 4M    INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 250 Gb
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  87)   Starting SPAdes, built from refs/heads/spades_3.13.0, git revision 8ea46659e9b2aca35444a808db550ac333006f8b
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  88)   Maximum k-mer length: 128
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  89)   Assembling dataset (/data/friesen/testdrive/agro-dir/spades_assembly/assembly/dataset.info) with K=27
  0:00:00.000     4M / 4M    INFO    General                 (main.cpp                  :  90)   Maximum # of threads to use (adjusted due to OMP capabilities): 1
  0:00:00.000     4M / 4M    INFO    General                 (launch.hpp                :  51)   SPAdes started
  0:00:00.000     4M / 4M    INFO    General                 (launch.hpp                :  58)   Starting from stage: construction
  0:00:00.000     4M / 4M    INFO    General                 (launch.hpp                :  65)   Two-step RR enabled: 0
  0:00:00.000     4M / 4M    INFO   StageManager             (stage.cpp                 : 132)   STAGE == de Bruijn graph construction
  0:00:00.008     4M / 4M    INFO    General                 (read_converter.hpp        :  77)   Converting reads to binary format for library #0 (takes a while)
  0:00:00.008     4M / 4M    INFO    General                 (read_converter.hpp        :  78)   Converting paired reads
  0:00:00.401    80M / 132M  INFO    General                 (binary_converter.hpp      :  93)   16384 reads processed
  0:00:00.606    92M / 132M  INFO    General                 (binary_converter.hpp      :  93)   32768 reads processed
  0:00:01.021   120M / 132M  INFO    General                 (binary_converter.hpp      :  93)   65536 reads processed
  0:00:02.071   184M / 184M  INFO    General                 (binary_converter.hpp      :  93)   131072 reads processed
  0:00:04.251   320M / 320M  INFO    General                 (binary_converter.hpp      :  93)   262144 reads processed
  0:00:06.537   464M / 464M  ERROR   General                 (paired_readers.hpp        :  56)   The number of right read-pairs is larger than the number of left read-pairs
  0:00:06.537   464M / 464M  ERROR   General                 (paired_readers.hpp        :  60)   Unequal number of read-pairs detected in the following files: /data/friesen/testdrive/agro-dir/spades_assem
bly/corrected_1.fastq.gz  /data/friesen/testdrive/agro-dir/spades_assembly/corrected_2.fastq.gz

== Error ==  system call for: "['/home/richard.white3/SPAdes-3.13.0-Linux/bin/spades-core', '/data/friesen/testdrive/agro-dir/spades_assembly/assembly/K27/configs/config.info']" finished abnormally, err c
ode: 255

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

# I have checked the inputs prior to error correction and it had the same number of reads. 
I tried to check the corrected reads but it formats them weird so I can 't check with fastqc.

uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Midline 'AAAAAAAADDDDDDDDGGGGGFHIHFHHHHHHHHHHHHIHHHHHHHIIHHHHHHHHHHHHHHHFGGEGEDEGEGCEGGEDGGGG?DG?GGGGGGGGGGGGGGGGGGGGGGGGGDGGGGGGGDGGGGGGGGGGGGGGGGGGGEGGGAGDGGEGGGGGGGGGGGGGGGGGAGGEGGGGGCEGGGGGGEEGGGGGGGGGGGGGGDGGGEEGGGGGGGGGGGGGGGGDA>DGGGGGAGGGGGDGGGG' didn't start with '+'
	at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:172)
	at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:76)
	at java.lang.Thread.run(Thread.java:748)

Failed to process file corrected_2.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: ID line didn't start with '@'
	at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:158)
	at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:76)
	at java.lang.Thread.run(Thread.java:748)

# I found this error code for spades 
https://www.biostars.org/p/311603/

Which states use a Try setting --phred-offset 33 or 64 manually and re-run. If you have recent sequence data then the offset will be 33 for sure. 
I can't put the --phred-offset flag in for spades for some reason. 

help?

**Comment by raw937** [comment]
Hello sleyn,

Its because my read pairs don't match. I figured it out. 
Use this program fastq_pair
https://github.com/linsalrob/fastq-pair
#make paired end reads match

#install fastq-pair
module load cmake
cd ~/fastq-pair-master/build
cmake -DCMAKE_INSTALL_PREFIX=$HOME ..   
make
make install

head -1051 FRIDec16A_C10_decon_R1.fastq >test_R1.fastq
head -1076 FRIDec16A_C10_decon_R2.fastq >test_R2.fastq

fastq_pair test_R1.fastq test_R2.fastq 
Writing the paired reads to test_R1.fastq.paired.fq and test_R2.fastq.paired.fq.
Writing the single reads to test_R1.fastq.single.fq and test_R2.fastq.single.fq
Left paired: 263		Right paired: 263
Left single: 0		Right single: 6

**Comment by sleyn** [comment]
Thanks!
I figured out this by running QC with trimmomatic and then run Unicycler with --no_correct parameter. It worked too with no errors.

**Comment by raw937** [comment]
sleyn, make sure to remove the phiX. Even when they say isn't on the lane it is. 
Also, bbduk is way better. Cleans the data better. Let me know if you need some commands. 

Cheers
Rick

**Comment by sleyn** [comment]
Thanks! Will try it.

**Comment by jhernandez1409** [comment]
Hi Rick, 
 I have the same error in Spades, however, I ran fastq_pair and everything came back "0". Do you have any idea what could be my problem?

Thanks in advance,

JoJo

**Comment by raw937** [comment]
hmm, odd. 
Try this: 
awk '{s++}END{print s/4}' file_R1.fastq
awk '{s++}END{print s/4}' file_R2.fastq

See if the counts match. 
If not re-run fastq_pair. Then rename the fixed files. 

If that doesn't work try this --no_correct parameter.

**Comment by KuldeepKumarSoni** [comment]
Can I run rnaspade.py in 8gb ram, 1tb hard disk
