### ISSUE TITLE
SPAdes crash at beginning of short reads, even with --temp-dir option

### ISSUE THREAD

**Issue by achang11** [rrwick/Unicycler#191]
Hello! I am having an issue where SPAdes keeps on crashing at the beginning of using short reads in Unicycler. 
I am running Unicycler on a Oracle VM with 18.04 Ubuntu. 
Here is the following command I am running:
/home/lts/SPAdes/bin/spades.py -1 /home/lts/Unicycler/sample_data/short_reads_1.fastq.gz -2 /home/lts/Unicycler/sample_data/short_reads_2.fastq.gz -o /media/sf_VMBioShare/uni_out/spades_assembly/read_correction --threads 6 --only-error-correction --tmp-dir /home/lts/spades_out

Below is the error message I am receiving from spades.log

``
System information:
  SPAdes version: 3.13.1
  Python version: 2.7.15
  OS: Linux-4.18.0-20-generic-x86_64-with-Ubuntu-18.04-bionic

Output dir: /media/sf_VMBioShare/uni_out/spades_assembly/read_correction
Mode: ONLY read error correction (without assembling)
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/home/lts/Unicycler/sample_data/short_reads_1.fastq.gz']
      right reads: ['/home/lts/Unicycler/sample_data/short_reads_2.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Other parameters:
  Dir for temp files: /home/lts/spades_out
  Threads: 6
  Memory limit (in Gb): 23

======= SPAdes pipeline started. Log can be found here: /media/sf_VMBioShare/uni_out/spades_assembly/read_correction/spades.log

===== Read error correction started. 

[Errno 1] Operation not permitted: '/media/sf_VMBioShare/uni_out/spades_assembly/read_correction/corrected/configs/config.info'
Traceback (most recent call last):
  File "/home/lts/SPAdes/bin/spades.py", line 797, in main
    ext_python_modules_home, only_compressing_is_needed, log)
  File "/home/lts/SPAdes/share/spades/spades_pipeline/hammer_logic.py", line 131, in run_hammer
    dir_util.copy_tree(os.path.join(configs_dir, "hammer"), dst_configs, preserve_times=False)
  File "/usr/lib/python2.7/distutils/dir_util.py", line 167, in copy_tree
    dry_run=dry_run)
  File "/usr/lib/python2.7/distutils/file_util.py", line 165, in copy_file
    os.chmod(dst, S_IMODE(st[ST_MODE]))
OSError: [Errno 1] Operation not permitted: '/media/sf_VMBioShare/uni_out/spades_assembly/read_correction/corrected/configs/config.info'

== Error ==  exception caught: <type 'exceptions.OSError'>
```
Any help with this matter would be greatly appreciated!

**Comment by dswan** [comment]
I don't think the issue is the setting of the temporary directory. Are you sure you have write permissions to the output directory? It looks like you're mounting an external filesystem from Virtualbox?

```
Output dir: /media/sf_VMBioShare/uni_out/spades_assembly/read_correction
[Errno 1] Operation not permitted: '/media/sf_VMBioShare/uni_out/spades_assembly/read_correction/corrected/configs/config.info'
```

What happens if you : ```touch media/sf_VMBioShare/uni_out/foo``` ?

**Comment by paul1000ton-coder** [comment]
Good morning. 

I was using Spades for a Metagenomic Analysis of my class of pregrade. I had the same problem, I use a subsystem of Linux in Windows. Could you help me please?

Thank you for your time.
