### ISSUE TITLE
Illegal Divsision by Zero while Building long read bridges

### ISSUE THREAD

**Issue by gitcruz** [rrwick/Unicycler#203]
Hi,
I have been running several hybrid assemblies with illumina and nanopore reads. There's a particular case with illumina depth 306.79 and nanopore depth 276.96 where I consistently get this error:
Traceback (most recent call last):
  File "/apps/PYTHON/3.6.3/bin/unicycler", line 11, in <module>
    load_entry_point('unicycler==0.4.6', 'console_scripts', 'unicycler')()
  File "/apps/PYTHON/3.6.3/lib/python3.6/site-packages/unicycler/unicycler.py", line 174, in main
    expected_linear_seqs, args.min_bridge_qual)
  File "/apps/PYTHON/3.6.3/lib/python3.6/site-packages/unicycler/bridge_long_read.py", line 552, in create_long_read_bridges
    for output in pool.imap_unordered(finalise_bridge, arg_list):
  File "/apps/PYTHON/3.6.3/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
  File "/apps/PYTHON/3.6.3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/apps/PYTHON/3.6.3/lib/python3.6/site-packages/unicycler/bridge_long_read.py", line 612, in finalise_bridge
    estimated_genome_size, expected_linear_seqs)
  File "/apps/PYTHON/3.6.3/lib/python3.6/site-packages/unicycler/bridge_long_read.py", line 299, in finalise
    read_count_factor = min(1.0, actual_read_count / expected_read_count)
ZeroDivisionError: float division by zero

Do you have an idea of how to overcome this?

Just in case is of some utility, these are the dependencies versions used:
Dependencies:
  Program         Version    Status
  spades.py       3.13.0     good
  racon           1.3.1      good
  makeblastdb     2.5.0+     good
  tblastn         2.5.0+     good
  bowtie2-build   2.2.9      good
  bowtie2         2.2.9      good
  samtools        1.9        good
  java            1.8.0_31   good
  pilon           1.21       good
  bcftools                   not used

Thanks in advance,
gitcruz

**Comment by SebastianMeyer1989** [comment]
Hello,
I don't know if there is any new insight in that matter, but I have exactly the same error for 35 of 3000 assemblies of simulated sequencing data. Same "ZeroDivisionError", same traceback messages.
If anyone knows something, please let me know. :)

Thanks alot


Sebastian

**Comment by rrwick** [comment]
Thanks for letting me know! I've put a fix (1800212) into the new version of Unicycler (v0.5.0).

Ryan
