### ISSUE TITLE
bowtie2-build error message

### ISSUE THREAD

**Issue by williamorsi** [rrwick/Unicycler#246]
Hello

I am running Unicycler for a hybrid assembly of illumina + nanopore reads, I am using a Macbook Pro (64bit) running Catalina. Unicycler is a great program for the hybrid assemblies, thank you for developing this!   I am running into a problem however I hope you can help me with?

So far I can get the assembler to complete, but not with the pilon correction.  When I run unicycler with the pilon correction module I get an error message that bowtie2-build is not found, however I can access bowtie2-build directly from the directory where I am running the unicycler script using the same path input 

--bowtie2_build_path ../../../bowtie2-2.4.1-macos-x86_64/bowtie2-build

And, when I run bowtie2-build using this same path from the terminal in the unicycler directory, then the bowtie2-build executable works.  So, the bowtie2-build executable is in the directory where it should be and it works.  But, then for some reason Unicycler does not find it.  

Furthermore, it is strange since bowtie2-build is given a 'good' status at the beginning of the run by unicycler indicating that it is where it should be:

Dependencies:
  Program         Version     Status  
  spades.py       3.13.0      good    
  racon           1.4.16      good    
  makeblastdb     2.2.26+     good    
  tblastn         2.2.26+     good    
  bowtie2-build   2.4.1       good    
  bowtie2         2.4.1       good    
  samtools        1.10        good    
  java            1.8.0_101   good    
  pilon           1.23        good    
  bcftools                    not used

Here is a printout of the error:

Polishing assembly with Pilon (2020-08-19 19:08:39)
    Unicycler now conducts multiple rounds of Pilon in an attempt to repair any remaining small-scale errors with the assembly.

Aligning reads to find appropriate insert size range...
Traceback (most recent call last):
  File "/usr/local/bin/unicycler", line 11, in <module>
    load_entry_point('unicycler==0.4.9b0', 'console_scripts', 'unicycler')()
  File "/Library/Python/3.8/site-packages/unicycler/unicycler.py", line 213, in main
    final_polish(graph, args, counter, long_reads_available)
  File "/Library/Python/3.8/site-packages/unicycler/unicycler.py", line 982, in final_polish
    polish_with_pilon_multiple_rounds(graph, graph, args, polish_dir, do_pilon_reassembly)
  File "/Library/Python/3.8/site-packages/unicycler/pilon_func.py", line 59, in polish_with_pilon_multiple_rounds
    insert_size_1st, insert_size_99th = get_insert_size_range(insert_size_graph, args, polish_dir)
  File "/Library/Python/3.8/site-packages/unicycler/pilon_func.py", line 107, in get_insert_size_range
    subprocess.check_output(bowtie2_build_command, stderr=subprocess.STDOUT)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '../../../bowtie2-2.4.1-macos-x86_64/bowtie2-build'

Can you please provide any assistance on why unicycler is not finding bowtie2-build , after it reports it as a 'good' status at the begginning?

Thanks!

Bill

**Comment by rrwick** [comment]
This is indeed a mysterious problem, but as discussed in issue #283, I'm dropping Pilon polishing in the most recent version of Unicycler (v0.5.0), and so Bowtie2 is no longer a dependency. So I'll close this issue, as it doesn't apply anymore.
