### ISSUE TITLE
original_depth is zero

### ISSUE THREAD

**Issue by maanmi** [rrwick/Unicycler#296]
Dear Ryan,

Right after UniCyler saves `005_bridges_applied.gfa`, I get the following error with two specific samples from a run of 4 samples. As far as I can tell the amount of both short and long read data is in similar range as samples of the same species we have run previously with success.

```
Traceback (most recent call last):
  File "/services/tools/anaconda3/4.4.0/bin/unicycler", line 8, in <module>
    sys.exit(main())
  File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/unicycler/unicycler.py", line 156, in main
    args.min_dead_end_size, graph, anchor_segments)
  File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/unicycler/assembly_graph.py", line 1363, in clean_up_after_bridging_2
    usedupness_scores[seg_num] = self.get_usedupness_score(seg_num, unbridged_graph)
  File "/services/tools/anaconda3/4.4.0/lib/python3.6/site-packages/unicycler/assembly_graph.py", line 1526, in get_usedupness_score
    depth_fraction_used = depth_used / original_depth
ZeroDivisionError: float division by zero
```

Any insights? Many thanks in advance.

**Comment by cmstouthamer** [comment]
Did you ever figure this one out? I'm experiencing the same problem.
