### ISSUE TITLE
unicycler error while saving 005_bridges_applied.gfa

### ISSUE THREAD

**Issue by xzguqgsntdzq** [rrwick/Unicycler#297]
I'm getting the following error:

Saving /unicycler/005_bridges_applied.gfa
Traceback (most recent call last):
  File "../unicycler-runner.py", line 21, in <module>
    main()
  File "../unicycler.py", line 156, in main
    args.min_dead_end_size, graph, anchor_segments)
  File "../assembly_graph.py", line 1363, in clean_up_after_bridging_2
    usedupness_scores[seg_num] = self.get_usedupness_score(seg_num, unbridged_graph)
  File "../assembly_graph.py", line 1526, in get_usedupness_score
    depth_fraction_used = depth_used / original_depth
ZeroDivisionError: float division by zero

I'm getting the same error for a number of samples, each is Illumina+Nanopore reads.

My setup is:
Unicycler version: v0.5.0
Program       Version   Status
  spades.py     3.14.0    good  
  racon         1.5.0     good  
  makeblastdb   2.11.0+   good  
  tblastn       2.11.0+   good

Any suggestions will be appreciated.

**Comment by galaxychan** [comment]
I got the same error.

I assembled the Illumina data and nanopore data. This "ZeroDivisionError" error occured in assembly process of one sample (the other four samples could execute right and get the assembly.fasta result). 
The output files was stopped with the file name "005_bridges_applied.gfa" and the log file just sudden end without recording any error message. 

The error information was listed below:

Traceback (most recent call last):
File "/usr/local/bin/unicycler", line 11, in
load_entry_point('unicycler==0.5.0', 'console_scripts', 'unicycler')()
File "/usr/local/lib/python3.6/site-packages/unicycler/unicycler.py", line 156, in main
args.min_dead_end_size, graph, anchor_segments)
File "/usr/local/lib/python3.6/site-packages/unicycler/assembly_graph.py", line 1363, in clean_up_after_bridging_2
usedupness_scores[seg_num] = self.get_usedupness_score(seg_num, unbridged_graph)
File "/usr/local/lib/python3.6/site-packages/unicycler/assembly_graph.py", line 1531, in get_usedupness_score
penalty = score_function(original_depth, 4.0)
File "/usr/local/lib/python3.6/site-packages/unicycler/misc.py", line 377, in score_function
return 1.0 - (half_score_val / (half_score_val + val))
ZeroDivisionError: float division by zero

Thank you a lot for any suggestion.

**Comment by cmstouthamer** [comment]
I have the same problem. Did you ever manage to figure this one out? I'm running version 0.5.0, same as above.
