### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1:invalid start byte

### ISSUE THREAD

**Issue by 540889956** [rrwick/Unicycler#309]
Hi All,
The issue shows below:
Using provided long read assembly instead of running Racon: MMH5in0E.fastq.gz

Traceback (most recent call last):
  File "/home//anaconda3/envs/unicycler/bin/unicycler", line 10, in <module>
    sys.exit(main())
  File "/home//anaconda3/envs/unicycler/lib/python3.10/site-packages/unicycler/unicycler.py", line 118, in main
    string_graph = make_miniasm_string_graph(graph, read_dict, long_read_filename,
  File "/home//anaconda3/envs/unicycler/lib/python3.10/site-packages/unicycler/miniasm_assembly.py", line 192, in make_miniasm_string_graph
    unitig_graph = StringGraph(existing_long_read_assembly)
  File "/home//anaconda3/envs/unicycler/lib/python3.10/site-packages/unicycler/string_graph.py", line 47, in __init__
    self.load_from_gfa(filename)
  File "/home//anaconda3/envs/unicycler/lib/python3.10/site-packages/unicycler/string_graph.py", line 53, in load_from_gfa
    for line in gfa_file:
  File "/home/anaconda3/envs/unicycler/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

I just dont know what happened during the assembly and don't know how to fix it? Can anyone help me?

**Comment by 540889956** [comment]
And did the progress finish? I guess it has finished but failed to output the results?
