### ISSUE TITLE
Illegal Divsision by Zero while Building long read bridges - continued error after update v0.5.0

### ISSUE THREAD

**Issue by amysiceloff** [rrwick/Unicycler#318]
I'm running into the same error as described in issue #203 (https://github.com/rrwick/Unicycler/issues/203) even after updating Unicycler to the most recent version. All dependencies are installed: 

Dependencies:
  Program       Version   Status
  spades.py     3.14.1    good  
  racon         1.4.13    good  
  makeblastdb   2.10.1+   good  
  tblastn       2.10.1+   good

**Comment by tougai** [comment]
i'm running into the same error with unicycler 0.5.0:
Traceback (most recent call last):
  File "/SD5/people/s1197826/.pyenv/versions/3.8.5/bin/unicycler", line 11, in <module>
    load_entry_point('unicycler==0.5.0', 'console_scripts', 'unicycler')()
  File "/SD5/people/s1197826/.pyenv/versions/3.8.5/lib/python3.8/site-packages/unicycler/unicycler.py", line 155, in main
    graph.clean_up_after_bridging_2(seg_nums_used_in_bridges, args.min_component_size,
  File "/SD5/people/s1197826/.pyenv/versions/3.8.5/lib/python3.8/site-packages/unicycler/assembly_graph.py", line 1363, in clean_up_after_bridging_2
    usedupness_scores[seg_num] = self.get_usedupness_score(seg_num, unbridged_graph)
  File "/SD5/people/s1197826/.pyenv/versions/3.8.5/lib/python3.8/site-packages/unicycler/assembly_graph.py", line 1526, in get_usedupness_score
    depth_fraction_used = depth_used / original_depth
ZeroDivisionError: float division by zero

**Comment by Joebio** [comment]
Hello there!
I realize this issue is quite old but still open. I encountered the same error using Unicycler v0.5.1 with Python v3.7.12. In my case, the problem seemed to be related to SPAdes version. I was initially using SPAdes v3.14.0 and ran into the error,  then after upgrading to SPAdes v3.15.5 the issue was resolved.
