### ISSUE TITLE
Spades throwing read length error

### ISSUE THREAD

**Issue by tomjevans** [rrwick/Unicycler#320]
Unicycler works perfectly with test sequences but using hybrid assembly with Illumina short and MinION long reads get following Spades error:
SPAdes maximum k-mer: 127
Traceback (most recent call last):
  File "/usr/local/bin/unicycler", line 33, in <module>
    sys.exit(load_entry_point('unicycler==0.5.0', 'console_scripts', 'unicycler')())
  File "/Library/Python/3.9/site-packages/unicycler/unicycler.py", line 76, in main
    graph = get_best_spades_graph(args.short1, args.short2, args.unpaired, args.out,
  File "/Library/Python/3.9/site-packages/unicycler/spades_func.py", line 47, in get_best_spades_graph
    kmer_range = get_kmer_range(kmers, short1, short2, short_unpaired, spades_dir, kmer_count,
  File "/Library/Python/3.9/site-packages/unicycler/spades_func.py", line 363, in get_kmer_range
    median_read_length = read_lengths[len(read_lengths) // 2 - 1]
IndexError: list index out of range

Using older version of Unicycler these sequences worked perfectly. ? not sure what the problem is. Grateful for any thoughts.

**Comment by tomjevans** [comment]
Solved
