### ISSUE TITLE
problem setup unicycler

### ISSUE THREAD

**Issue by unaren** [rrwick/Unicycler#44]
Hi,

Sorry I am new to this, so I am probably doing something stupid. I am trying to setup unicycler in a python 3.5 environment and under gcc 4.9.2. The setup seemed to finish fine with the big unicycler picture, but when I tried unicycler --help I get:

Traceback (most recent call last):
  File "./unicycler", line 11, in <module>
    load_entry_point('unicycler==0.4.0', 'console_scripts', 'unicycler')()
  File "/home/una/applications/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/home/una/applications/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/home/una/applications/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/una/applications/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/home/una/applications/anaconda3/envs/py35/lib/python3.5/site-packages/unicycler/unicycler.py", line 24, in <module>
    from .assembly_graph import AssemblyGraph
  File "/home/una/applications/anaconda3/envs/py35/lib/python3.5/site-packages/unicycler/assembly_graph.py", line 20, in <module>
    from .assembly_graph_segment import Segment
  File "/home/una/applications/anaconda3/envs/py35/lib/python3.5/site-packages/unicycler/assembly_graph_segment.py", line 19, in <module>
    from .bridge_long_read import LongReadBridge
  File "/home/una/applications/anaconda3/envs/py35/lib/python3.5/site-packages/unicycler/bridge_long_read.py", line 27, in <module>
    from .path_finding import get_best_paths_for_seq
  File "/home/una/applications/anaconda3/envs/py35/lib/python3.5/site-packages/unicycler/path_finding.py", line 23, in <module>
    from .cpp_wrappers import fully_global_alignment, path_alignment
  File "/home/una/applications/anaconda3/envs/py35/lib/python3.5/site-packages/unicycler/cpp_wrappers.py", line 28, in <module>
    C_LIB = CDLL(SO_FILE_FULL)
  File "/home/una/applications/anaconda3/envs/py35/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/una/applications/anaconda3/envs/py35/lib/python3.5/site-packages/unicycler/cpp_functions.so: undefined symbol: gzopen

I googled around, some people suggest it maybe zlib related, but I have zlip installed (1.2.8, I think), so probably wrong.

Thanks for your help.
-una

**Comment by rrwick** [comment]
Hi Una,

I'm not sure if I can be much help here - I'm not great with this sort of thing. It does in fact seem to be an issue with zlib, but with run time linking. My first thought is that you system doesn't have zlib in the right place, or maybe it doesn't know where to look and you need to set something in LD_LIBRARY_PATH...? Like I said, this stuff isn't my forte, so maybe a sys admin at your site will be more help.

Can you double-check that Unicycler's C++ functions can in fact compile okay? Just navigate to the Unicycler directory (the one you'd make by cloning Unicycler from Github) and run `make`. Does that finish without an error?

If that works, let's see if you can run Unicycler from it that same directory (i.e. running it without installing it). From that directory try: `./unicycler-runner.py --help`

Let me know how you go with those and we can dig deeper.

Ryan

**Comment by rrwick** [comment]
One other thought: some users founds that the Makefile needed tweaking to fix a zlib issue, and I've put the change into Unicycler's development branch. Maybe try cloning and building from that branch? Those changes will make it into v0.4.1 soon.

**Comment by unaren** [comment]
Thanks!!! I will give it a go.
Una

**Comment by rrwick** [comment]
Hi Una,

I've just made v0.4.1, so you don't need to go to the development branch to get that fix I mentioned - just grab the latest release or clone from the master branch. Let me know if it fixes it for you!

Ryan

**Comment by rrwick** [comment]
This issue is pretty old, so I'm going to close it now, but please let me know if you are still running into build issues, and I can look into it more.

Ryan

**Comment by unaren** [comment]
Crap sorry, we have changed our computer system to a central server over the last few months with an administrator installing all the packages. I haven’t tried again.

I am so sorry about this. Close the issue is fine.

Sorry again
-Una

**Comment by rrwick** [comment]
No worries :smile:

**Comment by unaren** [comment]
we are running unicycler and it is beautiful. :)


Thanks!

-una

________________________________
