### ISSUE TITLE
Failed polishing with Pilon

### ISSUE THREAD

**Issue by s4ria** [rrwick/Unicycler#63]
Hello!
I'm trying to assemble a number of bacterial genomes using Illumina and PacBio data on a Unix server with 250 Gb of RAM. Unfortunately, Unicycler always fails in the polishing Pilon polishing step with the following error message:
```
Pilon polish round 1
Unable to polish assembly using Pilon: Pilon encountered an error:
Pilon version 1.22 Wed Mar 15 16:38:30 2017 -0400
Genome: 1_polish_input.fasta
Fixing snps, indels
Input genome size: 5910851
Processing 1:1-5255328
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.broadinstitute.pilon.BaseSum.<init>(BaseSum.scala:23)
        at org.broadinstitute.pilon.PileUp.<init>(PileUp.scala:26)
        at org.broadinstitute.pilon.PileUpRegion$$anonfun$1.apply$mcVI$sp(PileUpRegion.scala:29)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at org.broadinstitute.pilon.PileUpRegion.<init>(PileUpRegion.scala:29)
        at org.broadinstitute.pilon.GenomeRegion.initializePileUps(GenomeRegion.scala:137)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$processRegions$4.apply(GenomeFile.scala:110)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$processRegions$4.apply(GenomeFile.scala:108)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Is this a bug or is there something I can do to overcome this issue?

Cheers!

**Comment by rrwick** [comment]
Hi Anna,

I'm not very good with Java stuff, but the `java.lang.OutOfMemoryError` makes me think that maybe your system's Java is configured to use too little memory by default. I have previously made a Bash script to call Pilon (so I can use the command `pilon` instead of `java -jar pilon-1.22.jar` which is ugly), and in such a script you can set the memory allowance for Java.

Try this: make a text file called `pilon` with these contents, replacing `/path/to/` with the path of your Pilon jar file:
```
#!/bin/sh
exec java -Xmx16384m -jar /path/to/pilon-1.22.jar "$@"
```
Make it executable (`chmod +x pilon`) and put it somewhere in your path (like `/usr/local/bin` or `~/.local/bin`) and try Unicycler again. Unicycler should pick up your new Pilon script and use that instead. You can verify that Unicycler found it by running Unicycler with `--verbosity 2` and checking the dependencies list at the start of the program.

I think 16 gigabytes of memory should be plenty for Pilon, so hopefully it will work! If not, then we dig deeper. Let me know how you go!

Ryan

**Comment by s4ria** [comment]
It worked like a charm! 

Anna

**Comment by rrwick** [comment]
Glad to hear it!

**Comment by EpiDemos82** [comment]
I recently ran into this problem with the conda installation of Unicycler.  It seems like I fixed it by changing the default Java memory options for Pilon, which is located in the file /anaconda3/envs/(env-name)/bin/pilon.  I changed the default_jvm_mem_opts = ['-Xms512m', '-Xmx1g'] to ['-Xms2g', '-Xmx8g'].  For larger genomes, this could probably be bumped up to 16g as Ryan suggested.
